remote_theme: daattali/beautiful-jekyll@main
plugins:
- jekyll-remote-theme

title: Marcus Gray
description: Some basic examples of client interfaces to a computer vision API

author:
  name: Jeremy Howard
